title:              Raj's Blog
email:              rajessvee@gmail.com
description:        A Mini Blog
author:             Rajpreet Singh
baseurl:            ""
url:                "https://rajxsv.github.io"

# Social Profiles
twitter_username:   RajVirdi15
github_username:    rajxsv
facebook_username:  raj.virdi.15
instagram_username:  rajxsv
linkedin_username:  rajpreet-singh-b8200a224

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
